# Generated by Django 6.0 on 2025-12-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted"),
        ),
        migrations.AddField(
            model_name="folder",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="deleted at"
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted"),
        ),
    ]
